// lib/llm/mock-llm-provider.ts
// Drop-in mock used when DEEPSEEK_API_KEY is absent/placeholder. Returns a
// contextually-shaped, clearly-labelled response so the app is fully usable in
// development without spending tokens. Mirrors the live provider's interface.

import type { LLMProvider, LLMChatParams } from "./types";

export class MockLLMProvider implements LLMProvider {
  readonly mode = "mock" as const;
  readonly name = "mock-llm";

  async chat(params: LLMChatParams): Promise<string> {
    // Simulate realistic latency.
    await new Promise((r) => setTimeout(r, 400 + Math.floor(Math.random() * 600)));

    const lastUser = [...params.messages].reverse().find((m) => m.role === "user");
    const q = (lastUser?.content ?? "").slice(0, 200);

    return [
      "[MOCK AI — set DEEPSEEK_API_KEY for live responses]",
      "",
      `I received your question: "${q}".`,
      "",
      "Here is how I'd approach it:",
      "1. Restate the problem and identify the inputs/outputs.",
      "2. Outline the method (e.g. data prep, model/analysis, validation).",
      "3. Implement incrementally and check intermediate results.",
      "",
      "_This is placeholder text generated by the mock LLM provider._",
    ].join("\n");
  }
}
